-- Initial schema for PostgreSQL.
--
-- Generated by Hibernate ORM 6.5.3 (PostgreSQLDialect) from the JPA entities in
-- com.study.synopsi.model, then tidied by hand: constraints carry stable names
-- instead of Hibernate's random suffixes, and the per-column CHECK constraints
-- Hibernate emits for @Enumerated(EnumType.STRING) columns are left out on
-- purpose. Hibernate's ddl-auto=validate does not inspect CHECK constraints, so
-- a new enum constant would pass startup validation and then fail on insert at
-- runtime; the enum types already restrict the values the application writes.
--
-- Column types are exactly what Hibernate validates against: bigint identity
-- ids, varchar(n) with the declared lengths, text for columnDefinition TEXT,
-- timestamp(6) for LocalDateTime, double precision for Double, boolean, integer.

create table sources (
    id                bigint generated by default as identity primary key,
    name              varchar(200)  not null,
    base_url          varchar(500)  not null,
    description       text,
    credibility_score double precision,
    language          varchar(100),
    country           varchar(100),
    source_type       varchar(50),
    is_active         boolean       not null,
    created_at        timestamp(6)  not null,
    updated_at        timestamp(6)  not null,
    constraint uk_sources_name unique (name)
);

create table topics (
    id              bigint generated by default as identity primary key,
    name            varchar(100) not null,
    description     varchar(500),
    slug            varchar(100),
    parent_topic_id bigint,
    is_active       boolean      not null,
    created_at      timestamp(6) not null,
    updated_at      timestamp(6) not null,
    constraint uk_topics_name unique (name),
    constraint uk_topics_slug unique (slug),
    constraint fk_topics_parent_topic foreign key (parent_topic_id) references topics
);

create table users (
    id                 bigint generated by default as identity primary key,
    username           varchar(50)  not null,
    email              varchar(100) not null,
    password           varchar(255) not null,
    first_name         varchar(100),
    last_name          varchar(100),
    role               varchar(255) not null,
    enabled            boolean      not null,
    account_locked     boolean      not null,
    created_at         timestamp(6) not null,
    updated_at         timestamp(6) not null,
    last_login_at      timestamp(6),
    reset_token        varchar(100),
    reset_token_expiry timestamp(6),
    preferences        text,
    constraint uk_users_username unique (username),
    constraint uk_users_email unique (email)
);

create table feeds (
    id                     bigint generated by default as identity primary key,
    source_id              bigint        not null,
    feed_url               varchar(2048) not null,
    feed_type              varchar(255)  not null,
    title                  varchar(200),
    description            text,
    topic_id               bigint,
    crawl_frequency_minutes integer      not null,
    last_crawled           timestamp(6),
    last_successful_crawl  timestamp(6),
    last_failed_crawl      timestamp(6),
    last_error             text,
    is_active              boolean       not null,
    priority               integer       not null,
    failure_count          integer       not null,
    created_at             timestamp(6)  not null,
    updated_at             timestamp(6)  not null,
    constraint uk_feeds_feed_url unique (feed_url),
    constraint fk_feeds_source foreign key (source_id) references sources,
    constraint fk_feeds_topic foreign key (topic_id) references topics
);

create index idx_feed_last_crawled on feeds (last_crawled);
create index idx_feed_is_active on feeds (is_active);

create table articles (
    id                bigint generated by default as identity primary key,
    title             varchar(500)  not null,
    original_url      varchar(2048) not null,
    content           text,
    publication_date  timestamp(6)  not null,
    author            varchar(200),
    image_url         varchar(2048),
    description       text,
    status            varchar(255)  not null,
    read_time_minutes integer,
    language          varchar(100),
    created_at        timestamp(6)  not null,
    updated_at        timestamp(6)  not null,
    feed_id           bigint        not null,
    constraint uk_articles_original_url unique (original_url),
    constraint fk_articles_feed foreign key (feed_id) references feeds
);

create index idx_article_publication_date on articles (publication_date);
create index idx_article_feed_id on articles (feed_id);
create index idx_article_created_at on articles (created_at);

create table article_topics (
    id              bigint generated by default as identity primary key,
    article_id      bigint       not null,
    topic_id        bigint       not null,
    relevance_score double precision,
    is_primary      boolean      not null,
    created_at      timestamp(6) not null,
    constraint uk_article_topics_article_topic unique (article_id, topic_id),
    constraint fk_article_topics_article foreign key (article_id) references articles,
    constraint fk_article_topics_topic foreign key (topic_id) references topics
);

create table summaries (
    id                 bigint generated by default as identity primary key,
    article_id         bigint       not null,
    user_id            bigint,
    summary_text       text         not null,
    summary_type       varchar(255) not null,
    summary_length     varchar(255) not null,
    model_version      varchar(100),
    generated_at       timestamp(6) not null,
    token_count        integer,
    status             varchar(255) not null,
    error_message      text,
    regeneration_count integer      not null,
    created_at         timestamp(6) not null,
    updated_at         timestamp(6) not null,
    constraint fk_summaries_article foreign key (article_id) references articles,
    constraint fk_summaries_user foreign key (user_id) references users
);

create index idx_summary_article_user on summaries (article_id, user_id);
create index idx_summary_status on summaries (status);
create index idx_summary_generated_at on summaries (generated_at);

create table summary_jobs (
    id             bigint generated by default as identity primary key,
    article_id     bigint       not null,
    user_id        bigint,
    summary_type   varchar(255) not null,
    summary_length varchar(255) not null,
    status         varchar(255) not null,
    priority       integer      not null,
    attempts       integer      not null,
    max_attempts   integer      not null,
    error_message  text,
    worker_job_id  varchar(255),
    submitted_at   timestamp(6) not null,
    started_at     timestamp(6),
    completed_at   timestamp(6),
    created_at     timestamp(6) not null,
    updated_at     timestamp(6) not null,
    constraint fk_summary_jobs_article foreign key (article_id) references articles,
    constraint fk_summary_jobs_user foreign key (user_id) references users
);

create index idx_job_status on summary_jobs (status);
create index idx_job_article on summary_jobs (article_id);
create index idx_job_submitted_at on summary_jobs (submitted_at);
create index idx_job_priority on summary_jobs (priority);

create table reading_history (
    id                    bigint generated by default as identity primary key,
    user_id               bigint       not null,
    article_id            bigint       not null,
    read_at               timestamp(6) not null,
    time_spent_seconds    integer,
    completion_percentage integer,
    last_accessed_at      timestamp(6),
    access_count          integer      not null,
    constraint uk_reading_history_user_article unique (user_id, article_id),
    constraint fk_reading_history_user foreign key (user_id) references users,
    constraint fk_reading_history_article foreign key (article_id) references articles
);

create index idx_reading_history_user on reading_history (user_id);
create index idx_reading_history_article on reading_history (article_id);
create index idx_reading_history_read_at on reading_history (read_at);

create table user_article_feedback (
    id            bigint generated by default as identity primary key,
    user_id       bigint       not null,
    article_id    bigint       not null,
    feedback_type varchar(255) not null,
    rating        integer,
    comment       text,
    created_at    timestamp(6) not null,
    updated_at    timestamp(6) not null,
    constraint uk_user_article_feedback_user_article_type unique (user_id, article_id, feedback_type),
    constraint fk_user_article_feedback_user foreign key (user_id) references users,
    constraint fk_user_article_feedback_article foreign key (article_id) references articles
);

create index idx_feedback_user on user_article_feedback (user_id);
create index idx_feedback_article on user_article_feedback (article_id);
create index idx_feedback_type on user_article_feedback (feedback_type);

create table user_preferences (
    id             bigint generated by default as identity primary key,
    user_id        bigint       not null,
    topic_id       bigint       not null,
    interest_level varchar(255) not null,
    is_active      boolean      not null,
    created_at     timestamp(6) not null,
    updated_at     timestamp(6) not null,
    constraint uk_user_preferences_user_topic unique (user_id, topic_id),
    constraint fk_user_preferences_user foreign key (user_id) references users,
    constraint fk_user_preferences_topic foreign key (topic_id) references topics
);
