apiVersion: batch/v1
kind: CronJob
metadata:
  name: synopsi-summarization
spec:
  schedule: "*/10 * * * *"  # Every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: summarization
              image: synopsi-summarization:latest
              command: ["python", "summarization/main.py"]
          restartPolicy: OnFailure