name: API CI

on:
  push:
    branches:
      - main
    paths:
      - 'synopsi-api/**'
      - '.github/workflows/api-ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'synopsi-api/**'
      - '.github/workflows/api-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew :synopsi-api:clean :synopsi-api:test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: synopsi-api/build/test-results/test/
          retention-days: 30

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: synopsi-api/build/reports/tests/test/
          retention-days: 30